version: '2'

services:
  omada:
    image: r4mmer/omada-controller
    container_name: omada-controller
    build:
      context: .
    ports:
      - "8088:8088"
      - "8043:8043"
    volumes:
      - data:/opt/tplink/EAPController/data
      - work:/opt/tplink/EAPController/work
      - logs:/opt/tplink/EAPController/logs

volumes:
  data:
  work:
  logs:
